#!/usr/bin/env python

import os
CURPATH = os.path.dirname(os.path.abspath(__file__))

import logging
logfile = os.path.join(CURPATH, 'agkyra.log')
logger = logging.getLogger('agkyra')
handler = logging.FileHandler(logfile)
formatter = logging.Formatter("%(levelname)s:%(asctime)s:%(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.INFO)

from agkyra import gui
gui.run()
