#!/usr/bin/env python
# Copyright (C) 2015 GRNET S.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

CURPATH = os.path.dirname(os.path.realpath(__file__))

try:
    from agkyra.cli import AgkyraCLI
except ImportError:
    LIBPATH = os.path.join(CURPATH, "lib")
    sys.path.insert(0, LIBPATH)
    from agkyra.cli import AgkyraCLI


if __name__ == "__main__":
    args = AgkyraCLI.parse_args()
    agkcli = AgkyraCLI(parsed_args=args)
    agkcli.onecmd(' '.join(args.cmd))
